import miraibg from "../assets/images/Mirai-bg.jpg"
import mirai from "../assets/images/Mirai.jpeg"

const movies = [
  {
    id: 1,
    title: "Avengers: Endgame",
    genre: "Action, Sci-Fi",
    duration: "3h 2m",
    rating: 8.4,
    votes: 2500000,
    languages: ["English"],   // ✅ array
    certification: "UA",
    releaseDate: "2019-04-26",
    poster: mirai,
    background_img : miraibg,
    description: "The Avengers assemble once more to undo Thanos' destruction.",
    cast: ["Robert Downey Jr", "Chris Evans", "Scarlett Johansson"],
    combo: "🍿 Popcorn + Drink @ ₹199",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "9:00 PM"],
  },
  {
    id: 2,
    title: "RRR",
    genre: "Action, Drama",
    duration: "3h 5m",
    rating: 8.0,
    votes: 180000,
    languages: ["Telugu", "Hindi", "Tamil"],   // ✅ multiple
    certification: "UA",
    releaseDate: "2022-03-25",
    poster: "https://image.tmdb.org/t/p/w500/hthfI8qzS4Gg9kZIx0DVoYH68Jz.jpg",
    description: "A fictional story about two legendary revolutionaries.",
    cast: ["Ram Charan", "Jr NTR", "Alia Bhatt"],
    combo: "🥤 Coke + Popcorn @ ₹150",
    trailer: "https://www.youtube.com/watch?v=BNyUugH1VnY",
    showtimes: ["9:00 AM", "12:30 PM", "4:00 PM", "8:00 PM"],
  },
  {
    id: 3,
    title: "La La Land",
    genre: "Romance, Musical",
    duration: "2h 8m",
    rating: 8.0,
    votes: 600000,
    languages: ["English"],
    certification: "U",
    releaseDate: "2016-12-09",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    description: "A jazz pianist falls for an aspiring actress in Los Angeles.",
    cast: ["Ryan Gosling", "Emma Stone"],
    combo: "🍫 Nachos + Coke @ ₹180",
    trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
  },
  {
    id: 1,
    title: "Avengers: Endgame",
    genre: "Action, Sci-Fi",
    duration: "3h 2m",
    rating: 8.4,
    votes: 2500000,
    languages: ["English"],   // ✅ array
    certification: "UA",
    releaseDate: "2019-04-26",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    description: "The Avengers assemble once more to undo Thanos' destruction.",
    cast: ["Robert Downey Jr", "Chris Evans", "Scarlett Johansson"],
    combo: "🍿 Popcorn + Drink @ ₹199",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "9:00 PM"],
  },
  {
    id: 2,
    title: "RRR",
    genre: "Action, Drama",
    duration: "3h 5m",
    rating: 8.0,
    votes: 180000,
    languages: ["Telugu", "Hindi", "Tamil"],   // ✅ multiple
    certification: "UA",
    releaseDate: "2022-03-25",
    poster: "https://image.tmdb.org/t/p/w500/hthfI8qzS4Gg9kZIx0DVoYH68Jz.jpg",
    description: "A fictional story about two legendary revolutionaries.",
    cast: ["Ram Charan", "Jr NTR", "Alia Bhatt"],
    combo: "🥤 Coke + Popcorn @ ₹150",
    trailer: "https://www.youtube.com/watch?v=BNyUugH1VnY",
    showtimes: ["9:00 AM", "12:30 PM", "4:00 PM", "8:00 PM"],
  },
  {
    id: 3,
    title: "La La Land",
    genre: "Romance, Musical",
    duration: "2h 8m",
    rating: 8.0,
    votes: 600000,
    languages: ["English"],
    certification: "U",
    releaseDate: "2016-12-09",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    description: "A jazz pianist falls for an aspiring actress in Los Angeles.",
    cast: ["Ryan Gosling", "Emma Stone"],
    combo: "🍫 Nachos + Coke @ ₹180",
    trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
  },
  {
    id: 1,
    title: "Avengers: Endgame",
    genre: "Action, Sci-Fi",
    duration: "3h 2m",
    rating: 8.4,
    votes: 2500000,
    languages: ["English"],   // ✅ array
    certification: "UA",
    releaseDate: "2019-04-26",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    description: "The Avengers assemble once more to undo Thanos' destruction.",
    cast: ["Robert Downey Jr", "Chris Evans", "Scarlett Johansson"],
    combo: "🍿 Popcorn + Drink @ ₹199",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "9:00 PM"],
  },
  {
    id: 2,
    title: "RRR",
    genre: "Action, Drama",
    duration: "3h 5m",
    rating: 8.0,
    votes: 180000,
    languages: ["Telugu", "Hindi", "Tamil"],   // ✅ multiple
    certification: "UA",
    releaseDate: "2022-03-25",
    poster: "https://image.tmdb.org/t/p/w500/hthfI8qzS4Gg9kZIx0DVoYH68Jz.jpg",
    description: "A fictional story about two legendary revolutionaries.",
    cast: ["Ram Charan", "Jr NTR", "Alia Bhatt"],
    combo: "🥤 Coke + Popcorn @ ₹150",
    trailer: "https://www.youtube.com/watch?v=BNyUugH1VnY",
    showtimes: ["9:00 AM", "12:30 PM", "4:00 PM", "8:00 PM"],
  },
  {
    id: 3,
    title: "La La Land",
    genre: "Romance, Musical",
    duration: "2h 8m",
    rating: 8.0,
    votes: 600000,
    languages: ["English"],
    certification: "U",
    releaseDate: "2016-12-09",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    description: "A jazz pianist falls for an aspiring actress in Los Angeles.",
    cast: ["Ryan Gosling", "Emma Stone"],
    combo: "🍫 Nachos + Coke @ ₹180",
    trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
  }
  
];

export default movies;